name: 'test'

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 5'

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: ./Tests/run.sh ghdl ./Boards2.sh
    - run: ./Tests/run.sh VUnit python3 run.py -v
